public class biodatadiri {
  public static void main(String[] agrs) {
    // Data diri 
    // String untuk menyimpan teks 
    String nama = "Abi mael al rajab";
    String alamat = "Campalagian";
    int umur = 18;
      //Println itu na cetak baru pindah garis baru 
      System.out.println("-------------");
      System.out.println(" biodatadiri ");
      System.out.println("-------------");
      System.out.println("nama   : " + "abi mael al rajab"); 

      //Print itu na cetak tapi ndak pindah garis
      System.out.print("nama : ");
      System.out.println("Abi mael al rajab");

      //Printf itu na cetak dengan format
      System.out.printf("universitas  : %s%n","unsulbar");
      System.out.printf("fakultas     : %s%n","teknik");
      System.out.printf("prodi        : %s%n","informatika");
     
      /* %s = untuk teks/String
       * %d = untuk angka bulat/int
       * %n = untuk pindah baris
      */
  }
} 
