public class biodatadiri {
  public static void main(string[] agrs) {
  
    String nama = "Abi mael al rajab"
    String alamat = "Campalagian"
    int umur = "18"
    String hobi = "suka berpura-pura"
    String nomordana = "085124020464"
      
      System.out.println("-------------")
      System.out.println(" biodatadiri ")
      System.out.println("-------------")

      System.out.print("nama : ")
      System.out.print("Abi mael al rajab")
      System.out.print("alamat : ")
      System.out.print("Campalagian")
      System.out.print("umur : ")
      System.out.print("18")
      System.out.print("hobi : ")
      System.out.print("suka berpura-pura")
      System.out.print("nomordana : ")
      System.out.print("085124020464")
 
      System.out.printf("tahun lahir  : %d%n", 2008)
      System.out.printf("jenis kelamin: %s%n", laki-laki)
      System.out.printf("universitas  : %s%n", unsulbar)
      System.out.printf("fakultas     : %s%n", teknik)
      System.out.printf("prodi        : %s%n", informatika)
  }
}
