public class biodatadiri {
  public static void main(String[] agrs) {
    // Data diri 
    // String untuk menyimpan teks 
    String nama = "Abi mael al rajab";
    String alamat = "Campalagian";
    Int umur = "18"
      //Println itu na cetak baru pindah garis baru 
      System.out.println("-------------");
      System.out.println(" biodatadiri ");
      System.out.println("-------------");

      //Print itu na cetak tapi ndak pindah garis
      System.out.print("nama : ");
      System.out.print("Abi mael al rajab");
      System.out.print("alamat : ");
      System.out.print("Campalagian");
      System.out.print("umur : ");
      System.out.print("18")

      //Printf itu na cetak dengan format 
      System.out.printf("tahun lahir  : %d%n","2008")
      System.out.printf("jenis kelamin: %s%n","laki-laki");
      System.out.printf("universitas  : %s%n","unsulbar");
      System.out.printf("fakultas     : %s%n","teknik");
      System.out.printf("prodi        : %s%n","informatika");
     
      /* %s = untuk teks/String
       * %d = untuk angka bulat/Int
       * %n = untuk pindah baris
      */
  }
} 
